version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - mongo
volumes:
  mongo-data:
