version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    environment:
      APP_SERVER: ${APP_SERVER:-gunicorn}
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    volumes:
      - profile-photos:/app/backend/uploads/profile_photos
    command: >
      sh -c 'if [ "$APP_SERVER" = "flask" ]; then \
                flask --app backend.app run --host=0.0.0.0 --port 5000; \
              else \
                gunicorn -b 0.0.0.0:5000 -w ${WORKERS:-1} backend.app:app; \
              fi'
    depends_on:
      - mongo
volumes:
  mongo-data:
  profile-photos:
